# Generated by Django 5.1.1 on 2024-10-04 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 4, 3, 17, 10, 710800)),
        ),
    ]
